// payment.js (at the same level as payend.js or as per your directory structure, but assuming it's for exporting paidPlans)
export const paidPlans = [
  {
    id: "individual",
    name: "Individual",
    price: 2500,
    period: "/month",
    description: "For single branch pharmacies",
    features: [
      "Up to 1 Branches ",
      "2000 Transactions (Each Branch)",
      "5 Place Order (Each Branch)",
      "Order Status",
      "Order Acknowledge / Discrepancy",
      "Main Branch View Sub-Branches Order ",
      "Main Branch Dispatch Sub-Branches Order",
      "Expiry Report",
      "Sales Report",
      "Basic & Advanced Search",
      "Inventory Management",
      "Drug Price Comparison",
    ],
    buttonText: "Get Individual",
    buttonClass: "bg-blue-600 text-white hover:bg-blue-700",
  },
  {
    id: "basic",
    name: "Basic",
    price: 3000,
    period: "/month",
    description: "Essential tools for startup pharmacies",
    features: [
      "Up to 5 Branches ",
      "2000 Transactions (Each Branch)",
      "5 Place Order (Each Branch)",
      "Order Status",
      "Order Acknowledge / Discrepancy",
      "Main Branch View Sub-Branches Order ",
      "Main Branch Dispatch Sub-Branches Order",
      "Expiry Report",
      "Sales Report",
      "Basic & Advanced Search",
      "Inventory Management",
      "Drug Price Comparison",
    ],
    buttonText: "Get Basic",
    buttonClass: "bg-blue-600 text-white hover:bg-blue-700",
  },
  {
    id: "pro",
    name: "Pro",
    price: 3500,
    period: "/month",
    description: "Advanced tools for growing pharmacies",
    features: [
      "Up to 10 Branches ",
      "5000 Transactions (Each Branch)",
      "10 Place Order (Each Branch)",
      "Order Status",
      "Order Acknowledge / Discrepancy",
      "Main Branch View Sub-Branches Order ",
      "Main Branch Dispatch Sub-Branches Order",
      "Expiry Report",
      "Sales Report",
      "Main Branch View Sub-Branches Sale",
      "Basic & Advanced Search",
      "Main Branch View Search of Sub-Branches",
      "Inventory Management",
      "Permission Management by Main Branch",
      "Drug Price Comparison",
    ],
    buttonText: "Get Pro",
    buttonClass: "bg-blue-600 text-white hover:bg-blue-700",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 4000,
    period: "/month",
    description: "Full scalability for pharmacy chains",
    features: [
      "Unlimited Branches",
      "Unlimited Transactions",
      "Unlimited Place Order (Each Branch) ",
      "Order Status",
      "Order Acknowledge / Discrepancy",
      "Main Branch View Sub-Branches Order ",
      "Main Branch Dispatch Sub-Branches Order",
      "Expiry Report",
      "Sales Report (Daily/Weekly/Monthly/Yearly)",
      "Main Branch View Sub-Branches Sale",
      "Basic & Advanced Search",
      "Main Branch View Search of Sub-Branches",
      "Inventory Management",
      "Main Branch View Inventory of Sub-Branches",
      "Permission Management by Main Branch",
      "Drug Price Comparison",
      "Main Branch View Drug Price Comparison of Sub-Branches",
    ],
    buttonText: "Get Enterprise",
    buttonClass: "bg-blue-600 text-white hover:bg-purple-700",
  },
];